os: Visual Studio 2015

environment:
    matrix:
        - TARGET: x86_64-pc-windows-msvc
        - TARGET: i686-pc-windows-msvc

install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
    - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
    - SET PATH=%PATH%;C:\MinGW\bin
    - rustc -V
    - cargo -V

build: false
test_script:
    - cargo test

before_deploy:
    - cargo build --release
    - bash -c "mv ./target/release/rackety.exe ."
    - bash -c "tar zcvf rackety-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.tar.gz rackety.exe LICENSE"
    - appveyor PushArtifact rackety-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.tar.gz

deploy:
    release_description: Rackety $(appveyor_repo_tag_name)
    provider: GitHub
    auth_token:
        secure: 'Nf3lF14tVAvIseNi+mmCMuwLaUAf5QWEyr6ThCfJMwHKSSqNA3NTq2KhX4t6Lb14'
    artifact: /.*\.tar\.gz/
    force_update: true
    on:
        appveyor_repo_tag: true
